version: 2.1
jobs:
  build:
    working_directory: ~/twilio-runtime-spoke-api
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update npm to 6.14.14
          command: |
              sudo npm i -g npm@6.14.14
              npm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - deploy:
          if [[ ("${CIRCLE_BRANCH}" == "main") && ($VERSION != *"SNAPSHOT") ]]; then
            npm --loglevel silent run version | xargs -I {} git tag "v{}"
            git push origin --tags
          else
            echo "Skip as branch not main"
          fi
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: org-global
