version: 2.1

aliases:
  - &npmrc
    name: Populate .npmrc
    command: |
      echo "@spoke-ph:registry=https://registry.npmjs.org/" >> ~/.npmrc
      echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
      echo "audit-level=critical" >> ~/.npmrc
      echo "ignore-scripts=true" >> ~/.npmrc
  - &disable_ssh_strict_host
    name: Turn off StrictHostKeyChecking for github.com
    command: |
      mkdir -p ~/.ssh
      echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

jobs:
  build:
    working_directory: ~/twilio-runtime-spoke-api
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Update NPM
          command: |
            sudo npm i -g npm@10.9.2
            npm --version
      - run: *npmrc
      - run:
          name: Install build-scripts
          command: |
            mkdir ~/tools
            cd ~/tools
            npm install @spoke-ph/build-scripts@4
      - run:
          name: NPM Setup
          command: |
            export PATH="$HOME/tools/node_modules/.bin:$PATH"
            npm run setup:ci
      - run: *disable_ssh_strict_host
      - run:
          name: Check package.json version
          command: npx sp-check-released-version
      - run:
          name: Checking changelog
          command: npx sp-changelog
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
      - run:
          name: Tag Release
          command: npm run tag:version

workflows:
  build_test_deploy:
    jobs:
      - build:
          context: org-global
