name: Automated PR Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  auto-pr-review:
    uses: spoke-ph/build-scripts/.github/workflows/pr-review.yml@master
    secrets: inherit
