name: Automated Dependency Upgrade

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  auto-dep-upgrade:
    uses: spoke-ph/build-scripts/.github/workflows/dep-upgrade.yml@master
    secrets: inherit
